CloudFrontOAC:
  Type: AWS::CloudFront::OriginAccessControl
  Properties:
    OriginAccessControlConfig:
      Name: !Sub '${AWS::StackName}-oac'
      OriginAccessControlOriginType: 'apigateway'
      SigningBehavior: 'always'
      SigningProtocol: 'sigv4'

cdnVpc:
  Type: AWS::CloudFront::Distribution
  Properties:
    DistributionConfig:
      Enabled: true
      DefaultCacheBehavior:
        TargetOriginId: PrivateApiOrigin
        ViewerProtocolPolicy: redirect-to-https
        AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          - PUT
          - POST
          - PATCH
          - DELETE
        CachedMethods:
          - GET
          - HEAD
          - OPTIONS
        ForwardedValues:
          QueryString: true
          Headers:
            - Authorization
            - Host
          Cookies:
            Forward: all
      Origins:
        - Id: PrivateApiOrigin
          DomainName: !Sub '${privaterestApi}.execute-api.${AWS::Region}.amazonaws.com'
          #OriginPath: '/pre'
          CustomOriginConfig:
            HTTPSPort: 443
            OriginProtocolPolicy: https-only
            OriginSSLProtocols:
              - TLSv1.2
          OriginAccessControlId: !Ref CloudFrontOAC
      PriceClass: PriceClass_100
      ViewerCertificate:
        CloudFrontDefaultCertificate: true