enrichState:
  Type: AWS::StepFunctions::StateMachine
  Properties:
    StateMachineName: enrich-states-${self:provider.stage}
    StateMachineType: EXPRESS
    RoleArn: !GetAtt statesRole.Arn

    LoggingConfiguration:
      Destinations:
        - CloudWatchLogsLogGroup:
            LogGroupArn: !GetAtt enrichStateLogGroup.Arn
      IncludeExecutionData: true
      Level: ALL

    TracingConfiguration:
      Enabled: true

    DefinitionS3Location:
      Bucket: !Ref aslDefinitionsBucket
      Key: enrich-states-${self:provider.stage}.asl.json
      Version: ${env:S3_ENRICH_VERSION_ID}
  
enrichStateLogGroup:
  Type: AWS::Logs::LogGroup
  Properties:
    LogGroupName: !Join [ "/", [ "enrichStateLogGroup_${self:provider.stage}", enrichStateLogGroup]]
    RetentionInDays: 30

    ##include change


ForceUpdateHelper:
  Type: AWS::CloudFormation::CustomResource
  Properties:
    ServiceToken: !GetAtt ForceUpdateFunction.Arn
    UniqueId: !Ref "AWS::StackId"
    TimeStamp: !Ref TimeStamp