genaiState:
  Type: AWS::StepFunctions::StateMachine
  Properties:
    StateMachineName: gen-ai-states-${self:provider.stage}
    StateMachineType: STANDARD
    RoleArn: !GetAtt statesRole.Arn

    LoggingConfiguration:
      Destinations:
        - CloudWatchLogsLogGroup:
            LogGroupArn: !GetAtt statesLogGroup.Arn
      IncludeExecutionData: true
      Level: ALL

    TracingConfiguration:
      Enabled: true

    DefinitionS3Location:
      Bucket: !Ref aslDefinitionsBucket
      Key: gen-ai-states-${self:provider.stage}.asl.json
      Version: ${env:S3_GENAI_VERSION_ID}

statesLogGroup:
  Type: AWS::Logs::LogGroup
  Properties:
    LogGroupName: !Join [ "/", [ "statesLogGroup_${self:provider.stage}", statesLogGroup]]
    RetentionInDays: 30