testState:
  Type: AWS::StepFunctions::StateMachine
  Properties:
    StateMachineName: test-states-${self:provider.stage}
    StateMachineType: STANDARD
    RoleArn: !GetAtt statesRole.Arn

    LoggingConfiguration:
      Destinations:
        - CloudWatchLogsLogGroup:
            LogGroupArn: !GetAtt statesLogGroup.Arn
      IncludeExecutionData: true
      Level: ALL

    TracingConfiguration:
      Enabled: true

    DefinitionS3Location:
      Bucket: !Ref aslDefinitionsBucket
      Key: test.asl.json
  

    #DefinitionString:
    #  Fn::Transform:
    #    Name: AWS::Include
    #    Parameters:
    #      Location: ./iac/states/definitions/test.asl.json

    #DefinitionString:
    #  Fn::Sub: ${file(./iac/states/definitions/test.asl.json)}
    
    
    #${TEST_STATE_MACHINE_DEFINITION}

statesTestLogGroup:
  Type: AWS::Logs::LogGroup
  Properties:
    LogGroupName: !Join [ "/", [ "statesTestLogGroup_${self:provider.stage}", statesTestLogGroup]]
    RetentionInDays: 30