privaterestApi:
  Type: AWS::ApiGateway::RestApi
  Properties:
    Name: gen-ai-api-rest-private-${self:provider.stage}
    Description: 'REST API - GEN AI Exposition Layer PRIVATE ${self:provider.stage}'
    EndpointConfiguration:
      Types:
        - PRIVATE
      VpcEndpointIds:
        - !Ref ApiGatewayVpcEndpoint
    Policy:
      Version: '2012-10-17'
      Statement:
        - Effect: "Allow"
          Principal: "*"
          Action:
            - "execute-api:Invoke"
          Resource: "execute-api:/*"
        - Effect: "Deny"
          Principal: "*"
          Action:
            - "execute-api:Invoke"
          Resource: "execute-api:/*"
          Condition:
            StringNotEquals:
              aws:sourceVpce: !Ref privateApiVPCEndpoint

RootMethod:
  Type: AWS::ApiGateway::Method
  Properties:
    RestApiId: !Ref privaterestApi
    ResourceId: !GetAtt privaterestApi.RootResourceId
    HttpMethod: GET
    AuthorizationType: NONE
    Integration:
      Type: MOCK
      IntegrationHttpMethod: GET
      PassthroughBehavior: WHEN_NO_MATCH
      RequestTemplates:
        application/json: '{"statusCode": 200}'
      IntegrationResponses:
        - StatusCode: 200
          ResponseTemplates:
            application/json: |
              {
                "mensaje": "Bienvenido a la API Privada",
                "version": "1.0",
                "timestamp": "$context.requestTime"
              }
    MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'



privaterestApiDeploy:
  Type: 'AWS::ApiGateway::Deployment'
  DependsOn: RootMethod
  Properties:
    RestApiId: !Ref privaterestApi
    Description: !Sub "REST API - GEN AI Exposition Layer  PRIVATE${self:provider.stage}"
    StageName: ${self:provider.stage}

privateStage:  
  Type: AWS::ApiGateway::Stage
  DependsOn: privaterestApiDeploy
  Properties:
    StageName: ${self:provider.stage}
    RestApiId: !Ref privaterestApi
    DeploymentId: !Ref privaterestApiDeploy

privaterestApiRole:
  Type: 'AWS::IAM::Role'
  Properties:
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Action:
            - 'sts:AssumeRole'
          Effect: Allow
          Principal:
            Service:
              - apigateway.amazonaws.com
    Policies:
      - PolicyName: gen-ai-restapi-private-role-Policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:*
              Resource: "*"

            - Effect: Allow
              Action:
                - dynamodb:*
              Resource: "*"

              #Condition:
              #  StringNotEquals:
              #    'aws:SourceArn': !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'

              #Condition:
              #  StringEquals:
              #    'aws:SourceVpce': !Ref ApiGatewayVpcEndpoint


