aslDefinitionsBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: asl-definitions-${self:provider.stage}
    AccessControl: Private
    PublicAccessBlockConfiguration:
      BlockPublicAcls: true
      BlockPublicPolicy: false
      IgnorePublicAcls: true
      RestrictPublicBuckets: false
    BucketEncryption:
      ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
    VersioningConfiguration:
      Status: Enabled
    LifecycleConfiguration:
      Rules:
        - Id: KeepOnly3Versions
          Status: Enabled
          NoncurrentVersionExpiration:
            NewerNoncurrentVersions: 3
            NoncurrentDays: 1



