WebsiteBucket:
  Type: 'AWS::S3::Bucket'
  Properties:
    BucketName: gen-ai-website-${self:provider.stage}
    ObjectOwnership: BucketOwnerPreferred
    WebsiteConfiguration:
      IndexDocument: index.html
      ErrorDocument: error.html
    PublicAccessBlockConfiguration:
      BlockPublicAcls: false
      BlockPublicPolicy: false
      IgnorePublicAcls: false
      RestrictPublicBuckets: false

WebsiteBucketPolicy:
  Type: 'AWS::S3::BucketPolicy'
  Properties:
    Bucket: !Ref WebsiteBucket
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Sid: PublicReadAccess
          Effect: Allow
          Principal: '*'
          Action: 's3:GetObject'
          Resource: !Sub '${WebsiteBucket.Arn}/*'