s3Table:
  Type: AWS::S3Tables::TableBucket
  Properties:
    TableBucketName: s3table-genai-${self:provider.stage}
    

s3TableOutput:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: s3table-output-${self:provider.stage}
    AccessControl: Private
    PublicAccessBlockConfiguration:
      BlockPublicAcls: true
      BlockPublicPolicy: true
      IgnorePublicAcls: true
      RestrictPublicBuckets: true
    BucketEncryption:
      ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
    VersioningConfiguration:
      Status: Enabled