privateModel:
  Type: "AWS::DynamoDB::Table"
  Properties:
    TableName: privateTable-${self:provider.stage}
    AttributeDefinitions:
      - AttributeName: idnot
        AttributeType: S
      - AttributeName: ownernot
        AttributeType: S
    KeySchema:
      - AttributeName: idnot
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: ownerIndex
        KeySchema:
          - AttributeName: ownernot
            KeyType: HASH
        Projection:
          ProjectionType: ALL
    BillingMode: PAY_PER_REQUEST
    ResourcePolicy:
      PolicyDocument: {
        "Version": "2012-10-17",
        "Id": "PolicyId",
        "Statement": [
          {
            "Sid": "AccessToSpecificVPCEOnly",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "dynamodb:*",
            "Resource": "arn:aws:dynamodb:eu-west-1:178934116267:table/privateTable-pre",
            "Condition": {
              "StringEquals": {
                "aws:sourceVpce": "vpce-025698fb63bd31a78"
              }
            }
          }
        ]
      }