sessionsBedrock:
  Type: "AWS::DynamoDB::Table"
  Properties:
    TableName: sessions-bedrock-${self:provider.stage}
    AttributeDefinitions:
      - AttributeName: sessionId
        AttributeType: S
      - AttributeName: timestamp
        AttributeType: S
    KeySchema:
      - AttributeName: sessionId
        KeyType: HASH
      - AttributeName: timestamp
        KeyType: RANGE
    BillingMode: PAY_PER_REQUEST
    TimeToLiveSpecification:
      AttributeName: ttl
      Enabled: true
    