putVector:
  Type: AWS::Lambda::Function
  Properties:
  Code:
    ZipFile: |
      import boto3 
      import json 
      from typing import Dict, Any

      s3vectors = boto3.client('s3vectors', region_name='eu-central-1')

      def handler(event: Dict[str, Any], _context) -> str:

          s3vectors.put_vectors( vectorBucketName="channy-vector-bucket",
          indexName="channy-vector-index", 
          vectors=[
          {"key": "v1", "data": {"float32": event.get('embedding')}, "metadata": {"id": event.get('key'), "source_text": event.get('key'), "genre":"documents"}}
          ],
          )
          return { "statusCode": 200, "body": json.dumps({"message": "Vector added successfully"})}

  Description: AWS Lambda function to put vector un S3-Vectors
  FunctionName: putVector
  Handler: index.lambda_handler
  MemorySize: 256
  Role: arn:aws:iam::178934116267:role/AlseaLambdaFullAccess
  Runtime: python3.13
  Architectures:
    - arm64
  Timeout: 60