strandsDeps:
  Type: AWS::Lambda::LayerVersion
  Properties:
    LayerName: strands-deps-${self:provider.stage}
    Description: Python dependencies for Strands Agents
    CompatibleRuntimes:
      - python3.12
    CompatibleArchitectures:
      - aarch64
    Content:
      ZipFile: packaging/dependencies.zip

  
