name: Deploy Gen AI
on:
  push:
    branches:
      - pre
env:
  AWS_REGION : "eu-west-1"
  AWS_SECONDARY_REGION : "us-east-1"
  STAGE: ${{ github.head_ref || github.ref_name }} 
  SERVERLESS_ACCESS_KEY: ${{ secrets.SLS_KEY }}
  GITHUB_CONTEXT: ${{ toJson(github) }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
permissions:
  id-token: write   
  contents: read    
jobs:

  Deploy-GEN-AI-COMPONENTS:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASUME }}
          role-session-name: ${{ secrets.ROLE_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Install Serverless Framework 🔧
        run: npm install -g serverless

      - name: Install NPM dependencies 📦
        run: yarn install

      #- name: Build Frontend 🚀 🔥
      #  run: cd src/menuapp && ls && yarn install && yarn build && cd build/ 

      #- name: Deploy Frontend 🚀 🔥
      #  run: cd src/promptui aws s3 cp --recursive --acl public-read --exclude *.map --exclude index.html --expires '2031-01-01T00:00:00Z' *.* s3://gen-ai-website-${{ env.STAGE }} && aws s3 cp --acl public-read index.html s3://gen-ai-website-${{ env.STAGE }}/index.html && cd ../..
      
      - name: Copy ASL definitions to S3 🚀 🔥
        run: |
          aws s3 cp iac/states/definitions/test.asl.json  s3://asl-definitions-${{ env.STAGE }}/test-${{ env.STAGE }}.asl.json
          aws s3 cp iac/states/definitions/gen-ai-states.asl.json  s3://asl-definitions-${{ env.STAGE }}/gen-ai-states-${{ env.STAGE }}.asl.json
          aws s3 cp iac/states/definitions/enrich-state.asl.json  s3://asl-definitions-${{ env.STAGE }}/enrich-states-${{ env.STAGE }}.asl.json
          

      - name: Get ENRICH S3 object version ID
        id: get-version-enrichment-sfn
        run: |
          # Get the latest version ID of the object
          VERSION_ID=$(aws s3api list-object-versions \
            --bucket asl-definitions-${{ env.STAGE }} \
            --prefix enrich-states-${{ env.STAGE }}.asl.json \
            --query 'Versions[0].VersionId' \
            --output text)
            
          # Set as output variable
          echo "enrich_version_id=$VERSION_ID" >> $GITHUB_OUTPUT
            
          # Also print for debugging
          echo "Retrieved version ID FOR ENRICH: $VERSION_ID"

      - name: Get GEN S3 object version ID
        id: get-version-gen-ai-sfn
        run: |
          # Get the latest version ID of the object
          VERSION_ID2=$(aws s3api list-object-versions \
            --bucket asl-definitions-${{ env.STAGE }} \
            --prefix gen-ai-states-${{ env.STAGE }}.asl.json \
            --query 'Versions[0].VersionId' \
            --output text)
              
          # Set as output variable
          echo "genai_version_id=$VERSION_ID2" >> $GITHUB_OUTPUT
              
          # Also print for debugging
          echo "Retrieved version ID for GEN AI: $VERSION_ID2"
      
      #- name: Install Rust 🦀  
      #  run: | 
      #    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      #    source $HOME/.cargo/env
      #    rustup target add aarch64-unknown-linux-musl #x86_64-unknown-linux-musl 


      #- name: Install Cargo Lambda Plugin 🦀 👾
      #  run: pip3 install cargo-lambda

      - name: Creating BootStrap Layer 👾
        run: |
            cd src/python/
            mkdir -p lambda-layer/python
            pip install -r requests strands-agents  strands-agents-tools --platform manylinux2014_x86_64 --only-binary=:all: -t lambda-layer/python
            cd lambda-layer
            zip -r ../strands-layer.zip python/
            cd ..
            aws s3 cp strands-layer.zip s3://strands-dependencies-${{ env.STAGE }}
            cd ../..


          #  aws s3 cp layer.zip s3://strands-dependencies-${{ env.STAGE }}/layers/

        #  pip install -r requirements.txt -t python/lib/python3.13/site-packages


  #          python3 -m venv .venv
  #          source .venv/bin/activate
  #          pip3 install -r requirements.txt --platform manylinux2014_aarch64 --target ./package --only-binary=:all:
  #          cd package
  #          zip -r ../bootstrap.zip . -x "*.pyc" -x "*.pyo" -x "*__pycache__*" -x "tests/*" -x "docs/*" 
  #          cd ../../../..


      #- name: Create package FAISS LLRT 😎
      #  run: cd src/llrt/faiss && zip -r faiss.zip . && cd ../../..
      

      #- name: Add execution permission to REPLACE VARABLES 😎
      #  run: chmod +x replace_variables.sh

      #- name: Replace variables 😎
      #  run: ./replace_variables.sh -t iac/states/test.yml -v TEST_STATE_MACHINE_DEFINITION -s iac/states/definitions/test.asl.json 

      #- name: validate replaces 😎
      #  run: cat iac/states/test.yml

      - name: Deploy GEN-AI reference  (🌐 → ☁️⚡ → 🚪🔒 → 🔗 → ⚖️ → 🏢🔐)
        run: serverless deploy --stage ${{ env.STAGE }} --region ${{ env.AWS_REGION }}
        env:
          S3_ENRICH_VERSION_ID: ${{ steps.get-version-enrichment-sfn.outputs.enrich_version_id }}
          S3_GENAI_VERSION_ID: ${{ steps.get-version-gen-ai-sfn.outputs.genai_version_id }}

      - name: Prune old versions 🧹
        run: serverless prune -n 1 --stage ${{ env.STAGE }}